### ISSUE TITLE
Request to re-publish the "include-files" filter

### ISSUE THREAD

**Issue by dkabus** [pandoc-ext/info#1]
Please re-publish this filter to include other files in Markdown.

https://github.com/pandoc/lua-filters/tree/master/include-files

Thank you!

**Comment by wlupton** [comment]
Sorry for the delay. This seems like a reasonable request! So (if I understand you correctly) you'd expect this to show up as a new <https://github.com/pandoc-ext/include-files> repository... yes?

**Comment by dkabus** [comment]
Exactly, I think this filter is really useful! Thank you

**Comment by wlupton** [comment]
OK. I think I have permission to create this new repo, and will aim to do so (preserving history from the old one) within the next few days. Any comment @tarleb?

**Comment by wlupton** [comment]
I've created <https://github.com/pandoc-ext/include-files>. Does it look OK?

**Comment by dkabus** [comment]
Looks great! 👍
