### ISSUE TITLE
Kindly publish fonts-and-alignment filter in pandoc-ext

### ISSUE THREAD

**Issue by nandac** [pandoc-ext/info#2]
Dear Folks,

I created the following filter a called [fonts-and-alignment](https://github.com/nandac/fonts-and-alignment)  for Pandoc and was not able to publish it in the [lua-filters](https://github.com/pandoc/lua-filters/tree/master) repository because it was being retired.

Would it be possible to get it published in the new [pandoc-ext](https://github.com/pandoc-ext) repository at this point?

Kindly let me know what the process is.

**Comment by nandac** [comment]
@alerque @tarleb @wlupton  Is it possible for the filter above to be published as a Pandoc filter?

If any more work is needed kindly let me know.

**Comment by wlupton** [comment]
I'd be happy to add it but I don't really know what the acceptance criteria are (or what the procedures are). However, I guess it's best just to do it and then ask for forgiveness (if necessary).

Please can you give me permission to move the repo (I guess you need to add me as a collaborator with write access, or maybe I need more access than that... not sure)? I think this is the best way to add it to pandoc-ext rather that cloning and pushing, because GH will know what's happened and can handle redirects and so on.

**Comment by nandac** [comment]
@wlupton Thank you for your reply.

I have added you as a collaborator and you should have received an invitation to the repository.

It does not look like I can give you any permissions until you accept the invitation but let us play it by ear.

**Comment by wlupton** [comment]
Thanks. I accepted the invitation.

**Comment by nandac** [comment]
@wlupton Can you confirm that you have the access you need? I don't see you having any restrictions as a collaborator on the project.

KIndly let me know.

**Comment by wlupton** [comment]
I don't believe that I have the necessary access. I think that, when I go to <https://github.com/nandac/fonts-and-alignment>, I need to see a "Settings" tab so I can scroll down to the Danger Zone and transfer ownership.

What do you see when you go to the repo's settings and select "Collaborators and teams"? I'm guessing that you see me, but what role do I have? I'm not sure what role I need... perhaps "Admin"?

**Comment by nandac** [comment]
@wlupton I see the Settings tab I could transfer ownership to someone else. I do not see a way to elevate your privileges as the repository is already public.

The only way for you to have access would be to transfer ownership to you but then I would lose access.

**Comment by wlupton** [comment]
Can you transfer ownership to the pandoc-ext organisation? I had assumed not, but maybe it'll generate a request for the organisation to accept ownership.

BTW, the repo being public surely doesn't (per se) mean that you can't elevate my privileges. "public" means "publicly readable". What role do I have?

**Comment by alerque** [comment]
@wlupton The way with the fewest shenanigans is that @nandoc needs to be invited to join this or so he can transfer the repo here. The alternative approach is a bit harder because it it hard to elevate your privs enough inside his personal account namespace for you to be able to transfer out. It can be done but it takes a few steps.

He does not have to be an org owner or even have privs on other repos, he just needs the create-repo priv on the org in order to transfer in.

**Comment by wlupton** [comment]
Thanks @alerque! I see that I have permission to create repos, but I don't think that I can add a new member of the organisation (and I think that you have the same rights as me). Do we need one of the owners to step in here?

**Comment by nandac** [comment]
@wlupton Can I help in any way. I am quite happy to transfer ownership to an org or someone else. I can do this as long as I have clear steps to follow.

**Comment by wlupton** [comment]
Sorry for the delay. I had been assuming that we needed to get the admins involved, but yes we can do this via a third party. I have an organisation that we should be able to use, and will look into giving you the necessary access to transfer your repo to it. I won't be able to do this until later tomorrow or Monday.

**Comment by wlupton** [comment]
@nandac i've invited you to [the other organisation](https://github.com/honu-ltd). If you accept the invite, you should be able to move your repo to this org, and I will then move it to pandoc-ext (at which point I'll remove you from the org). OK?

**Comment by nandac** [comment]
@wlupton I have moved the repository. The link is here: https://github.com/honu-ltd/fonts-and-alignment

**Comment by wlupton** [comment]
Thanks. I've moved it to https://github.com/pandoc-ext/fonts-and-alignment and removed you as a honu-ltd collaborator.

Sorry it took so long! Does anything else need to be done from your point of view?

**Comment by nandac** [comment]
Thanks for your efforts @wlupton I appreciate it.

On another note does this org allow the running of CI/CD GitHub workflows? Right now it shows as failed which I should either get passing or remove the badge altogether.

**Comment by wlupton** [comment]
I don't believe that I have sufficient access to change any CI/CD stuff. My ideal would be to give you the necessary access to this repo. I think that we now really do need to get some input from the admins, who are @tarleb and @jgm (maybe one or more of the maintainers could be promoted to admin, or maybe the maintainers and admins need to have a private discussion about this).

**Comment by jgm** [comment]
I've changed it to allow first-time contributors who are not new to GH to run workflows.

**Comment by jgm** [comment]
That said, I'm not quite sure about the criteria for inclusion here either -- the repo was started by @tarleb who can probably comment further.

**Comment by tarleb** [comment]
We haven't yet formalized the criteria for inclusion. The approach that I'd been using was:

1. The filter must be useful
2. It must be easy to setup with Quarto
3. I'd be willing to maintain the filter if the original author isn't able to.

**Comment by wlupton** [comment]
Thanks. Could we also discuss (somewhere) the rights and responsibilities of the organization admins and maintainers? Perhaps admins and maintainers could use issues in an empty-ish private repo for this purpose?

**Comment by alerque** [comment]
GitHub orgs have a team discussion space. It doesn't seem to be enabled for this or / team and I don't have org ownership privs to enable it. I believe it should just be a checkbox to enable the team/org discussion space.

**Comment by tarleb** [comment]
I've enabled org-wide discussions: https://github.com/orgs/pandoc-ext/discussions

**Comment by wlupton** [comment]
Can we (and do we want to) have team-only discussions?

**Comment by alerque** [comment]
There used to be a thing called "team posts" tha were private to the team members. I just checked another org we we used them a little bit to verify with other admins before inviting new team members, but it looks like the entire feature has been sunset. It now offers me the ability to migrate the team posts to discussions and wants to know what repository to use. It also says the post visibility will change to match the repository settings not the previous team settings.

So I guess the answer is "no" we can't unless we get into adding private repositories. It seems to me in this case that might be of limited use, but if you still feel some venue should be found for private member discussions maybe open a new issue to that effect and we'll look into what is needed vs what is possible.

**Comment by wlupton** [comment]
I'm only thinking that discussions of how to manage the organization _might_ want to be private, but I don't feel this too strongly... I'm just thinking that it might be the case. Example: We might think that a given repo shouldn't be added but don't really want to stir any hornets nests (the sort of thing that might be an email discussion, except that we don't know or need to know each other's email addresses).

If we do want private discussions, then I think that associating them with a private repo is an ok solution.

**Comment by tarleb** [comment]
I'm okay with having (most of) these discussions in public. I also like the transparency that comes from this. For delicate issues we could still resort to mails.
